name: Standard

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - name: Install dependencies
        run: npm ci
      - name: Check types
        run: npm run type:check
      - name: Check format, lint and imports
        run: npm run check-all
      - name: Test
        run: npm run test:coverage
      - name: Build
        run: npm run build
      - name: Publish
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
